### ISSUE TITLE
how to download the data outside of R?

### ISSUE THREAD

**Issue by randomgambit** [EmilHvitfeldt/textdata#28]
Hello and thanks for this great package! 

Unfortunately my corporate firewall prevents me from downloading the data from within R (I can download the file manually with the browser).

What should I do to make it work? 

Thanks!

**Comment by EmilHvitfeldt** [comment]
What you can do if you still want to use **textdata**  as normal is to first run your function with the argument `return_path = TRUE`. This will give you the location **textdata** expects the downloaded file to placed. Then you just manually download the file and place it in that folder (don't unzip, rename or otherwise change the file). Then run the function like normal and it should work.

**Comment by randomgambit** [comment]
amazing! thanks. you should document this on your website. Many of us are behind firewalls...

**Comment by randomgambit** [comment]
@EmilHvitfeldt Actually I did so, but the package still asks me to download the file.

calling `library(textadata)` again shows a strange message without any actual menu

> 
> Enter an item from the menu, or 0 to exit
> Selection:

What should I do?
Thanks!

**Comment by EmilHvitfeldt** [comment]
Okay, I should have fixed the problem this time. 

- run the function you want with `return_path = TRUE`
- place the file you downloaded in that directory.
- run the function with `manual_download = TRUE` (this should perform the post download processing)
- run the function like normal.
