### ISSUE TITLE
lexicon_afinn() is forcing https, but url is http

### ISSUE THREAD

**Issue by sbw78** [EmilHvitfeldt/textdata#31]
I get a 404 error when I try to download the AFINN sentiment lexicon. It looks like https is being forced somewhere in the function, but I can't figure out how to fix it myself.  I've tried editing the `textdata::catalogue` data.frame but that did not work.  The only way I was able to fix it was to manually download the zip file.

**Comment by EmilHvitfeldt** [comment]
that you for bringing this to my attention!

This has been fixed in the dev branch here on Github where you can download the version

```r
remotes::install_github("EmilHvitfeldt/textdata")
```
<img width="636" alt="Screen Shot 2020-05-03 at 10 21 30 AM" src="https://user-images.githubusercontent.com/14034784/80920966-13e1e100-8d28-11ea-821f-0cdb683d59f2.png">
